language: python
python:
- '2.7'
install:
- pip install -r django/mysite/requirements.txt
- pip install flake8
script:
- invoke test_all
before_deploy:
- cd unicorn
- ng build
deploy:
  - provider: s3
    access_key_id:
      secure: CFcxH9epdv/Gr+vMTW66lL70NaMv6swjRZVV60hgEV4DaST0OIuJwlikvbMrI0Gw5zOCOdtQaBA/SXZ0Lzp7b5PCgNdldMuyI6iQ/wCQtEgjGeLU/vqS/9PON8Gpl7HHw4KoPC2XJMU4FmmPBo1tc7td9zdvOkvFWe6IuLiquijOurf+JXrLyuK3uKOjv8Jg12mW5zfra9yVDxXrWrA/qTLxRBOfuIV7pckLMzhByIZNoHzOofmVZCiIb2XMNEiM5+ngnqPi4ealRXtzrbqGy5fBmJoeBk0PAtcXrQAjhKWeggUTkCBPxWSSC70dkbm1L+k/2YBQToNoONoyT+wvsbRigeAjcpqGyP9afk11VVJNNvJtiz65O83BMADOkeASN29B6o/a5C/uZZhAWqmdE7QSJ785nJTdLZD4wH8SLuM/8TlT9bHcAV+M9jX/EqgYuJA7MlU0R1FOJTEmbE4EW3xzlW6M8EnZOrdyTO+LSDVx5ysjHhpHUFHKUYfaBb6ACsosi7lKJNdfzC9Ylh1HY3PhIyhcpun8O53U64khdFLGa0jyEeFlnO7Y77PjL5NcFb0xhBxEGbFkuVMYT0wC2F/SstZEWNiOkiVRQ4lfGenEBS64urix/x6pBqrpXKGNqHEjF3QrZeNgrpX+3UFcb3zLgTU9ptGGREge0GzHCvA=
    secret_access_key:
      secure: hl22OZWN6kXBdagki0G+do2ZTlPjSdWs+VXfWRQJtNcs19IC7GjUi49jV8/CTVgk3Kvces+F1v68l7N6degLDjm5OJxyxkM0IbcRC8SENZoanOZO1UBJg0fvdgrxikWtruo98/JBzNkNmU10JUOVsC3hoHkkABj3DoZE/0YoDwwylahE/e0y/yYMAvHhYSwUhEcxjBfKXzOddUOb2xUMELYjo9nlg033/sE9dR9GovanncPoh8gP+sHgMOzpYPDNIBA6eK5sJOb4pdyONaGEVs9GfKV8qpbH13QyvSuaB0a6gxNtG/Rl4UyfibPpFCCCYuqehOOzTbY1cDXICS7abjUxY/QuRXZV6ulG0omrNwKhs7jcfOLdffaRZWmUIfBM/kC+fmabfPk7D4zhzmLfpK0I6FkwNfheakWVUp42QI0MRlbU5GiP40fK5U3pblbCtmAi3c2+Ds2blaLj1Uq53NzkMedYBj+meI+PCRa4WsCgnD26PvMy/tZLaVEfcvM6fKq7VvYtlMzACMwbJHsYak7n1EMp0ZoRbvJh8XQYviykhaXNlzKfRn+35NroDR7wCWcNd6iYc7sgd9yOhziJThGfUTr6AdH5TFrWbOQw73Zzzu0YXBNZONnFGTUkbT1mt4RXOqR4Ew0jd9goSeZRwwEGn/Jxgm6nDA9ZlXknesA=
    bucket: cavalierdani-angular
    local_dir: unicorn/build
    on:
      branch: master
  - provider: s3
    access_key_id:
      secure: CFcxH9epdv/Gr+vMTW66lL70NaMv6swjRZVV60hgEV4DaST0OIuJwlikvbMrI0Gw5zOCOdtQaBA/SXZ0Lzp7b5PCgNdldMuyI6iQ/wCQtEgjGeLU/vqS/9PON8Gpl7HHw4KoPC2XJMU4FmmPBo1tc7td9zdvOkvFWe6IuLiquijOurf+JXrLyuK3uKOjv8Jg12mW5zfra9yVDxXrWrA/qTLxRBOfuIV7pckLMzhByIZNoHzOofmVZCiIb2XMNEiM5+ngnqPi4ealRXtzrbqGy5fBmJoeBk0PAtcXrQAjhKWeggUTkCBPxWSSC70dkbm1L+k/2YBQToNoONoyT+wvsbRigeAjcpqGyP9afk11VVJNNvJtiz65O83BMADOkeASN29B6o/a5C/uZZhAWqmdE7QSJ785nJTdLZD4wH8SLuM/8TlT9bHcAV+M9jX/EqgYuJA7MlU0R1FOJTEmbE4EW3xzlW6M8EnZOrdyTO+LSDVx5ysjHhpHUFHKUYfaBb6ACsosi7lKJNdfzC9Ylh1HY3PhIyhcpun8O53U64khdFLGa0jyEeFlnO7Y77PjL5NcFb0xhBxEGbFkuVMYT0wC2F/SstZEWNiOkiVRQ4lfGenEBS64urix/x6pBqrpXKGNqHEjF3QrZeNgrpX+3UFcb3zLgTU9ptGGREge0GzHCvA=
    secret_access_key:
      secure: hl22OZWN6kXBdagki0G+do2ZTlPjSdWs+VXfWRQJtNcs19IC7GjUi49jV8/CTVgk3Kvces+F1v68l7N6degLDjm5OJxyxkM0IbcRC8SENZoanOZO1UBJg0fvdgrxikWtruo98/JBzNkNmU10JUOVsC3hoHkkABj3DoZE/0YoDwwylahE/e0y/yYMAvHhYSwUhEcxjBfKXzOddUOb2xUMELYjo9nlg033/sE9dR9GovanncPoh8gP+sHgMOzpYPDNIBA6eK5sJOb4pdyONaGEVs9GfKV8qpbH13QyvSuaB0a6gxNtG/Rl4UyfibPpFCCCYuqehOOzTbY1cDXICS7abjUxY/QuRXZV6ulG0omrNwKhs7jcfOLdffaRZWmUIfBM/kC+fmabfPk7D4zhzmLfpK0I6FkwNfheakWVUp42QI0MRlbU5GiP40fK5U3pblbCtmAi3c2+Ds2blaLj1Uq53NzkMedYBj+meI+PCRa4WsCgnD26PvMy/tZLaVEfcvM6fKq7VvYtlMzACMwbJHsYak7n1EMp0ZoRbvJh8XQYviykhaXNlzKfRn+35NroDR7wCWcNd6iYc7sgd9yOhziJThGfUTr6AdH5TFrWbOQw73Zzzu0YXBNZONnFGTUkbT1mt4RXOqR4Ew0jd9goSeZRwwEGn/Jxgm6nDA9ZlXknesA=
    bucket: staging-cavalierdani-angular
    local_dir: unicorn/build
    on:
      branch: staging
